version: "3"
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    container_name: "cur-app"
    tty: true
    stdin_open: true
